CREATE TABLE visits (
  ID SERIAL PRIMARY KEY,
  page VARCHAR(255) NOT NULL,
  language VARCHAR(255) NOT NULL,
  browser VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  visitorID VARCHAR(255) NOT NULL
);